# Generated by Django 3.1.7 on 2021-04-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0003_auto_20210402_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
