# Generated by Django 3.2 on 2021-07-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=3000)),
                ('url', models.CharField(blank=True, max_length=3000)),
                ('image', models.CharField(blank=True, max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=3000)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_scanner.favorite')),
            ],
        ),
        migrations.DeleteModel(
            name='PriceUrls',
        ),
    ]
