# Generated by Django 3.1.7 on 2021-07-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_scanner', '0003_auto_20210712_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
