# Generated by Django 3.2 on 2021-07-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_scanner', '0006_auto_20210713_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='test',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
