# Generated by Django 3.2 on 2021-07-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_scanner', '0007_favorite_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='price_scanner.favorite'),
        ),
    ]
