# Generated by Django 3.2 on 2021-07-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_scanner', '0008_alter_price_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='test',
        ),
    ]
