# Generated by Django 3.2 on 2021-04-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_scanner', '0003_yelprestaurant_yelptotals'),
    ]

    operations = [
        migrations.AddField(
            model_name='resyrestaurant',
            name='test',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
