# Generated by Django 3.2 on 2021-04-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition_scanner', '0004_resyrestaurant_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resyrestaurant',
            name='test',
        ),
    ]
