# Generated by Django 3.2 on 2021-04-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_scanner', '0005_remove_resyrestaurant_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='resyrestaurant',
            name='url',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
