# Generated by Django 3.1.7 on 2021-04-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_scanner', '0007_alter_resyrestaurant_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelprestaurant',
            name='url',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
