# Generated by Django 3.2 on 2021-05-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_scanner', '0008_yelprestaurant_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resyrestaurant',
            name='neighborhood',
            field=models.CharField(max_length=3000),
        ),
    ]
