# Generated by Django 3.2 on 2021-05-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_scanner', '0010_alter_resyrestaurant_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='resyrestaurant',
            name='address',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
