# Generated by Django 3.1.7 on 2021-06-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition_scanner', '0011_resyrestaurant_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yelprestaurant',
            name='neighborhood',
        ),
    ]
