# Generated by Django 3.1.7 on 2021-06-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition_scanner', '0014_resycollections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResyCollections',
        ),
    ]
