# Generated by Django 3.1.7 on 2021-06-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_scanner', '0015_delete_resycollections'),
    ]

    operations = [
        migrations.AddField(
            model_name='resyrestaurant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
