# Generated by Django 3.2 on 2021-07-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_scanner', '0016_resyrestaurant_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelprestaurant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
