# Generated by Django 3.1.2 on 2021-04-02 13:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablehost', '0002_remove_guest_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='slot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
    ]
