# Generated by Django 3.2 on 2021-07-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablehost', '0004_auto_20210731_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
