# Generated by Django 3.2 on 2021-07-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablehost', '0005_auto_20210731_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='guest',
        ),
    ]
