# Generated by Django 3.2 on 2021-07-31 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablehost', '0007_slot_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest', to='tablehost.guest'),
        ),
    ]
