# Generated by Django 3.2 on 2021-07-31 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablehost', '0009_alter_slot_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='tablehost.book'),
            preserve_default=False,
        ),
    ]
