# Generated by Django 3.2 on 2021-08-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablehost', '0013_alter_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='root_user',
        ),
        migrations.AddField(
            model_name='guest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
