# Generated by Django 3.1.7 on 2021-08-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablehost', '0014_auto_20210807_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#fff', max_length=1000)),
                ('label', models.CharField(default='', max_length=1000)),
                ('status_type', models.CharField(default='confirmation', max_length=1000)),
            ],
        ),
    ]
