# Generated by Django 3.2 on 2021-08-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablehost', '0015_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='guest', to='tablehost.guest'),
        ),
    ]
