# Generated by Django 3.2 on 2021-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablehost', '0017_auto_20210808_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
