# Generated by Django 3.2 on 2021-07-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
