# Generated by Django 3.2 on 2021-07-20 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0005_alter_player_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
    ]
