# Generated by Django 3.2 on 2021-07-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0006_auto_20210720_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
