# Generated by Django 3.1.7 on 2021-04-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resy_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resyrestaurant',
            name='resy_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='resyrestaurant',
            name='restaurant_name',
            field=models.CharField(max_length=3000),
        ),
    ]
