# Generated by Django 3.1.7 on 2021-04-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resy_scanner', '0002_auto_20210402_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='resyrestaurant',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='resyrestaurant',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
