# Generated by Django 3.1.7 on 2021-07-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=3000)),
                ('temp', models.IntegerField(blank=True, default=0, max_length=1000)),
                ('light', models.CharField(blank=True, default='sunny', max_length=3000)),
                ('humidity', models.IntegerField(blank=True, default=0, max_length=3000, null=True)),
                ('rain', models.IntegerField(blank=True, default=0, max_length=3000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
