# Generated by Django 3.1.7 on 2021-07-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_mate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='humidity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='rain',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='temp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
