# Generated by Django 3.2 on 2021-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_store', '0006_auto_20210808_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
